; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc < %s -mtriple=avr -verify-machineinstrs -stop-after=dead-mi-elimination | FileCheck %s

; This test shows the machine IR that is generated when lowering a shift
; operation to a loop.

define i32 @shl_i32_n(i32 %a, i32 %b) #0 {
  ; CHECK-LABEL: name: shl_i32_n
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $r23r22, $r25r24, $r19r18
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:dregs = COPY $r19r18
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:dregs = COPY $r25r24
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:dregs = COPY $r23r22
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr8 = COPY [[COPY]].sub_lo
  ; CHECK-NEXT:   RJMPk %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDRdRr:%[0-9]+]]:gpr8 = ADDRdRr %10, %10, implicit-def $sreg
  ; CHECK-NEXT:   [[ADCRdRr:%[0-9]+]]:gpr8 = ADCRdRr %9, %9, implicit-def $sreg, implicit $sreg
  ; CHECK-NEXT:   [[ADCRdRr1:%[0-9]+]]:gpr8 = ADCRdRr %8, %8, implicit-def $sreg, implicit $sreg
  ; CHECK-NEXT:   [[ADCRdRr2:%[0-9]+]]:gpr8 = ADCRdRr %7, %7, implicit-def $sreg, implicit $sreg
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2 (%ir-block.0):
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr8 = PHI [[COPY1]].sub_hi, %bb.0, [[ADCRdRr2]], %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr8 = PHI [[COPY1]].sub_lo, %bb.0, [[ADCRdRr1]], %bb.1
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gpr8 = PHI [[COPY2]].sub_hi, %bb.0, [[ADCRdRr]], %bb.1
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:gpr8 = PHI [[COPY2]].sub_lo, %bb.0, [[ADDRdRr]], %bb.1
  ; CHECK-NEXT:   [[PHI4:%[0-9]+]]:gpr8 = PHI [[COPY3]], %bb.0, %17, %bb.1
  ; CHECK-NEXT:   [[DECRd:%[0-9]+]]:gpr8 = DECRd [[PHI4]], implicit-def $sreg
  ; CHECK-NEXT:   BRPLk %bb.1, implicit $sreg
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3 (%ir-block.0):
  ; CHECK-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:dregs = REG_SEQUENCE [[PHI]], %subreg.sub_hi, [[PHI1]], %subreg.sub_lo
  ; CHECK-NEXT:   [[REG_SEQUENCE1:%[0-9]+]]:dregs = REG_SEQUENCE [[PHI2]], %subreg.sub_hi, [[PHI3]], %subreg.sub_lo
  ; CHECK-NEXT:   $r23r22 = COPY [[REG_SEQUENCE1]]
  ; CHECK-NEXT:   $r25r24 = COPY [[REG_SEQUENCE]]
  ; CHECK-NEXT:   RET implicit $r23r22, implicit $r25r24, implicit $r1
  %res = shl i32 %a, %b
  ret i32 %res
}
